### ISSUE TITLE
L4L lurk list usage

### ISSUE THREAD

**Issue by lurk24** [Sighmir/KustomBot#3]
I see the example command !L4L adds people to the l4l.json file

does the example implementation do anything with the channels in that list?

I was thinking there should be something similar to the spam module, maybe named lurk, that would define what it does with those files. does something like that already exist?

**Comment by Sighmir** [comment]
Hey I think I answered this on the other issue.

A lot of features that were added were originally a request from a friend, so some of them are tailored how he wanted them in the example, if you want to read the gererated l4l.json you can use: 
```js
let l4l = JSON.parse(fs.readFileSync('l4l.json', 'utf8'));
```
The list of names will be available on the l4l variable for you to use it however you want.

Check my answers on issue #2 if you need more details on how to install it.

If you have any questions or need help implementing some feature add me on Discord - Sighmir#1621.

**Comment by Sighmir** [comment]
The list was intended to be available for my friend to copy the channels in it to the config.json and spam.js. 

When he asked for that feature I don't think he wanted it to be automatic (?... I'm not sure.. maybe he just wanted to make it easier for me..).

It wouldn't be much harder to implement it, but things could run out of control with your bot automatically joining every new channel that types !l4l to spam it.
