### ISSUE TITLE
Please use secure communication by default

### ISSUE THREAD

**Issue by lurk24** [Sighmir/KustomBot#5]
Please enable ```secure: true``` within the connection string.

Here is a pull request that accomplishes this:
5e66b31de4e68b7aab02cdcb9fde8599485b1982

**Comment by lurk24** [comment]
Actually i think #4 the pull request... 5e66b31de4e68b7aab02cdcb9fde8599485b1982 is the code changes.

**Comment by Sighmir** [comment]
The project was converted to typescript and all control over tmi.js options is on the user end now :)
